name: Regression End-to-end tests
on: push
jobs:
  firefox-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
            browser : firefox

      - name: cypress tes  report for firefoxrun
        uses: actions/upload-artifact@v4
        with:
         name: mochaawesome report for firefox
         path: cypress/reports/html

  chrome-run:
    runs-on: ubuntu-22.04
    steps:
     - name: Checkout
       uses: actions/checkout@v4
        # Install npm dependencies, cache them correctly
        # and run all Cypress tests
     - name: Cypress run
       uses: cypress-io/github-action@v6
       with:
          browser : chrome  
     - name: cypress tes  report for chromerun
       uses: actions/upload-artifact@v4
       with:
         name: mochaawesome report for chrome
         path: cypress/reports/html